name: Build Android App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

      - name: chmod
      run: chmod +x gradlew

    - name: Install dependencies
      run: ./gradlew install

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ secrets.GITHUB_RELEASES_URL }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: app-debug.apk
        asset_content_type: application/vnd.android.package-archive
